version: "3.9"

services:
  temi_v:
    container_name: ${FRONTEND_CONTAINER_NAME}
    build:
      context: .
      dockerfile: client/Dockerfile
      target: build-stage
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
      - front-volume:/app/dist/
    command: /bin/sh -c "yarn serve"
    networks:
      - rpc-network

  temi_rpc:
    container_name: ${SERVICE_CONTAINER_NAME}
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      - SSL_CERT=/etc/nginx/ssl/live/${SERVER_DOMAIN_NAME}/fullchain.pem
      - SSL_KEY=/etc/nginx/ssl/live/${SERVER_DOMAIN_NAME}/privatekey.pem
    command:
      - ./binary/server
    volumes:
      - .:/opt
      - ./certbot/conf/:/etc/nginx/ssl/
    restart: always
    depends_on:
      - mongodb
    env_file:
      - .env
    ports:
      - ${SERVICE_PORT}:8000
    networks:
     - rpc-network

  envoy:
    container_name: envoy
    build:
      context: ./
      dockerfile: Dockerfile.envoy
    volumes:
      - ./envoy.yaml:/etc/envoy.yaml
      - ./certbot/conf/:/etc/nginx/ssl/
    ports:
      - ${ENVOY_PROXY_PORT}:8080
    networks:
      - rpc-network

  mongodb:
    image: mongo
    container_name: ${MONGO_CONTAINER_NAME}
    volumes:
      - ./mongodb:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60.27017/${MONGO_DATABASE} --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - rpc-network

  nginx:
    container_name: ${NGINX_CONTAINER_NAME}
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf/:ro
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - front-volume:/usr/share/nginx/html
    depends_on:
      - temi_v
      - temi_rpc
    ports:
      - "80:80"
      - "443:443"
    networks:
      - rpc-network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www/:/var/www/certbot/:rw

volumes:
  mongodb:
  front-volume:

networks:
  rpc-network: {}
