version: "3.9"

services:
  temi_rpc:
    container_name: ${SERVICE_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SSL_CERT=cert-volume/live/nbmfscafdcasc.xyz/fullchain.pem
      - SSL_KEY=cert-volume/live/nbmfscafdcasc.xyz/privatekey.pem
    command:
      - ./binary/server
    volumes:
      - .:/opt
      - cert-volume:/etc/nginx/ssl/:ro
    restart: always
    depends_on:
      - mongodb
    env_file:
      - .env
    ports:
      - ${SERVICE_PORT}:8000
    networks:
     - rpc-network

  envoy:
    container_name: envoy
    build:
      context: .
      dockerfile: Dockerfile.envoy
    volumes:
      - ./envoy.yaml:/etc/envoy.yaml
      - cert-volume:/etc/nginx/ssl/:ro
    ports:
      - ${ENVOY_PROXY_PORT}:8080
    networks:
      - rpc-network

  mongodb:
    image: mongo
    container_name: ${MONGO_CONTAINER_NAME}
    volumes:
      - ./mongodb:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60.27017/${MONGO_DATABASE} --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - rpc-network

  nginx:
    image: nginx:latest
    volumes:
#      - ./config/nginx.conf:/etc/nginx/nginx.conf/:ro
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
#    depends_on:
#      - temi_rpc
    ports:
      - "80:80"
      - "443:443"
    networks:
      - rpc-network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www/:/var/www/certbot/:rw

#secrets:
#  server.crt:
#    file: ./cert/server.crt
#  server.key:
#    file: ./cert/server.key

volumes:
  mongodb:
  cert-volume:

networks:
  rpc-network: {}

