// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.3
// source: metal-doors.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PostsRequest) Reset() {
	*x = PostsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metal_doors_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostsRequest) ProtoMessage() {}

func (x *PostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metal_doors_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostsRequest.ProtoReflect.Descriptor instead.
func (*PostsRequest) Descriptor() ([]byte, []int) {
	return file_metal_doors_proto_rawDescGZIP(), []int{0}
}

type PostsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Post `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PostsResponse) Reset() {
	*x = PostsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metal_doors_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostsResponse) ProtoMessage() {}

func (x *PostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metal_doors_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostsResponse.ProtoReflect.Descriptor instead.
func (*PostsResponse) Descriptor() ([]byte, []int) {
	return file_metal_doors_proto_rawDescGZIP(), []int{1}
}

func (x *PostsResponse) GetData() *Post {
	if x != nil {
		return x.Data
	}
	return nil
}

type Post struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title     string      `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Price     float32     `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Tags      []string    `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	InColors  []*InColors `protobuf:"bytes,5,rep,name=in_colors,json=inColors,proto3" json:"in_colors,omitempty"`
	InImages  []string    `protobuf:"bytes,6,rep,name=in_images,json=inImages,proto3" json:"in_images,omitempty"`
	OutImages []string    `protobuf:"bytes,7,rep,name=out_images,json=outImages,proto3" json:"out_images,omitempty"`
}

func (x *Post) Reset() {
	*x = Post{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metal_doors_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_metal_doors_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_metal_doors_proto_rawDescGZIP(), []int{2}
}

func (x *Post) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Post) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Post) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Post) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Post) GetInColors() []*InColors {
	if x != nil {
		return x.InColors
	}
	return nil
}

func (x *Post) GetInImages() []string {
	if x != nil {
		return x.InImages
	}
	return nil
}

func (x *Post) GetOutImages() []string {
	if x != nil {
		return x.OutImages
	}
	return nil
}

type InColors struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Color string `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
	Hex   string `protobuf:"bytes,2,opt,name=hex,proto3" json:"hex,omitempty"`
}

func (x *InColors) Reset() {
	*x = InColors{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metal_doors_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InColors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InColors) ProtoMessage() {}

func (x *InColors) ProtoReflect() protoreflect.Message {
	mi := &file_metal_doors_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InColors.ProtoReflect.Descriptor instead.
func (*InColors) Descriptor() ([]byte, []int) {
	return file_metal_doors_proto_rawDescGZIP(), []int{3}
}

func (x *InColors) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *InColors) GetHex() string {
	if x != nil {
		return x.Hex
	}
	return ""
}

type SingleMetalDoorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SingleMetalDoorRequest) Reset() {
	*x = SingleMetalDoorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metal_doors_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleMetalDoorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleMetalDoorRequest) ProtoMessage() {}

func (x *SingleMetalDoorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metal_doors_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleMetalDoorRequest.ProtoReflect.Descriptor instead.
func (*SingleMetalDoorRequest) Descriptor() ([]byte, []int) {
	return file_metal_doors_proto_rawDescGZIP(), []int{4}
}

func (x *SingleMetalDoorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SingleMetalDoorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string                            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                            `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Price          float32                           `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Specifications *Specifications                   `protobuf:"bytes,4,opt,name=specifications,proto3" json:"specifications,omitempty"`
	Variants       []*SingleMetalDoorResponseVariant `protobuf:"bytes,5,rep,name=variants,proto3" json:"variants,omitempty"`
	Tags           []string                          `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *SingleMetalDoorResponse) Reset() {
	*x = SingleMetalDoorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metal_doors_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleMetalDoorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleMetalDoorResponse) ProtoMessage() {}

func (x *SingleMetalDoorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metal_doors_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleMetalDoorResponse.ProtoReflect.Descriptor instead.
func (*SingleMetalDoorResponse) Descriptor() ([]byte, []int) {
	return file_metal_doors_proto_rawDescGZIP(), []int{5}
}

func (x *SingleMetalDoorResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SingleMetalDoorResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SingleMetalDoorResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SingleMetalDoorResponse) GetSpecifications() *Specifications {
	if x != nil {
		return x.Specifications
	}
	return nil
}

func (x *SingleMetalDoorResponse) GetVariants() []*SingleMetalDoorResponseVariant {
	if x != nil {
		return x.Variants
	}
	return nil
}

func (x *SingleMetalDoorResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Specifications struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height     float32 `protobuf:"fixed32,1,opt,name=height,proto3" json:"height,omitempty"`
	Metal      float32 `protobuf:"fixed32,2,opt,name=metal,proto3" json:"metal,omitempty"`
	Leaf       float32 `protobuf:"fixed32,3,opt,name=leaf,proto3" json:"leaf,omitempty"`
	UpperLock  string  `protobuf:"bytes,4,opt,name=upper_lock,json=upperLock,proto3" json:"upper_lock,omitempty"`
	LowerLock  string  `protobuf:"bytes,5,opt,name=lower_lock,json=lowerLock,proto3" json:"lower_lock,omitempty"`
	Valve      string  `protobuf:"bytes,6,opt,name=valve,proto3" json:"valve,omitempty"`
	Armor      string  `protobuf:"bytes,7,opt,name=armor,proto3" json:"armor,omitempty"`
	Cylinder   string  `protobuf:"bytes,8,opt,name=cylinder,proto3" json:"cylinder,omitempty"`
	Peephole   string  `protobuf:"bytes,9,opt,name=peephole,proto3" json:"peephole,omitempty"`
	Insulation string  `protobuf:"bytes,10,opt,name=insulation,proto3" json:"insulation,omitempty"`
	Sealer     string  `protobuf:"bytes,11,opt,name=sealer,proto3" json:"sealer,omitempty"`
	Handle     string  `protobuf:"bytes,12,opt,name=handle,proto3" json:"handle,omitempty"`
}

func (x *Specifications) Reset() {
	*x = Specifications{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metal_doors_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Specifications) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Specifications) ProtoMessage() {}

func (x *Specifications) ProtoReflect() protoreflect.Message {
	mi := &file_metal_doors_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Specifications.ProtoReflect.Descriptor instead.
func (*Specifications) Descriptor() ([]byte, []int) {
	return file_metal_doors_proto_rawDescGZIP(), []int{6}
}

func (x *Specifications) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Specifications) GetMetal() float32 {
	if x != nil {
		return x.Metal
	}
	return 0
}

func (x *Specifications) GetLeaf() float32 {
	if x != nil {
		return x.Leaf
	}
	return 0
}

func (x *Specifications) GetUpperLock() string {
	if x != nil {
		return x.UpperLock
	}
	return ""
}

func (x *Specifications) GetLowerLock() string {
	if x != nil {
		return x.LowerLock
	}
	return ""
}

func (x *Specifications) GetValve() string {
	if x != nil {
		return x.Valve
	}
	return ""
}

func (x *Specifications) GetArmor() string {
	if x != nil {
		return x.Armor
	}
	return ""
}

func (x *Specifications) GetCylinder() string {
	if x != nil {
		return x.Cylinder
	}
	return ""
}

func (x *Specifications) GetPeephole() string {
	if x != nil {
		return x.Peephole
	}
	return ""
}

func (x *Specifications) GetInsulation() string {
	if x != nil {
		return x.Insulation
	}
	return ""
}

func (x *Specifications) GetSealer() string {
	if x != nil {
		return x.Sealer
	}
	return ""
}

func (x *Specifications) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

type Variant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InColor   string   `protobuf:"bytes,1,opt,name=in_color,json=inColor,proto3" json:"in_color,omitempty"`
	OutColor  string   `protobuf:"bytes,2,opt,name=out_color,json=outColor,proto3" json:"out_color,omitempty"`
	InImages  []string `protobuf:"bytes,3,rep,name=in_images,json=inImages,proto3" json:"in_images,omitempty"`
	OutImages []string `protobuf:"bytes,4,rep,name=out_images,json=outImages,proto3" json:"out_images,omitempty"`
	Size      []*Size  `protobuf:"bytes,6,rep,name=size,proto3" json:"size,omitempty"`
	Hex       string   `protobuf:"bytes,7,opt,name=hex,proto3" json:"hex,omitempty"`
}

func (x *Variant) Reset() {
	*x = Variant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metal_doors_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Variant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variant) ProtoMessage() {}

func (x *Variant) ProtoReflect() protoreflect.Message {
	mi := &file_metal_doors_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variant.ProtoReflect.Descriptor instead.
func (*Variant) Descriptor() ([]byte, []int) {
	return file_metal_doors_proto_rawDescGZIP(), []int{7}
}

func (x *Variant) GetInColor() string {
	if x != nil {
		return x.InColor
	}
	return ""
}

func (x *Variant) GetOutColor() string {
	if x != nil {
		return x.OutColor
	}
	return ""
}

func (x *Variant) GetInImages() []string {
	if x != nil {
		return x.InImages
	}
	return nil
}

func (x *Variant) GetOutImages() []string {
	if x != nil {
		return x.OutImages
	}
	return nil
}

func (x *Variant) GetSize() []*Size {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *Variant) GetHex() string {
	if x != nil {
		return x.Hex
	}
	return ""
}

type Size struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Width int32       `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Side  string      `protobuf:"bytes,2,opt,name=side,proto3" json:"side,omitempty"`
	Data  []*SizeData `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *Size) Reset() {
	*x = Size{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metal_doors_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Size) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Size) ProtoMessage() {}

func (x *Size) ProtoReflect() protoreflect.Message {
	mi := &file_metal_doors_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Size.ProtoReflect.Descriptor instead.
func (*Size) Descriptor() ([]byte, []int) {
	return file_metal_doors_proto_rawDescGZIP(), []int{8}
}

func (x *Size) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Size) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *Size) GetData() []*SizeData {
	if x != nil {
		return x.Data
	}
	return nil
}

type SizeData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Serial         string `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	Dealer         string `protobuf:"bytes,2,opt,name=dealer,proto3" json:"dealer,omitempty"`
	State          string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Prepay         string `protobuf:"bytes,4,opt,name=prepay,proto3" json:"prepay,omitempty"`
	OrderDate      string `protobuf:"bytes,5,opt,name=order_date,json=orderDate,proto3" json:"order_date,omitempty"`
	ReadyDate      string `protobuf:"bytes,6,opt,name=ready_date,json=readyDate,proto3" json:"ready_date,omitempty"`
	ReserveEndDate string `protobuf:"bytes,7,opt,name=reserve_end_date,json=reserveEndDate,proto3" json:"reserve_end_date,omitempty"`
}

func (x *SizeData) Reset() {
	*x = SizeData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metal_doors_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SizeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeData) ProtoMessage() {}

func (x *SizeData) ProtoReflect() protoreflect.Message {
	mi := &file_metal_doors_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeData.ProtoReflect.Descriptor instead.
func (*SizeData) Descriptor() ([]byte, []int) {
	return file_metal_doors_proto_rawDescGZIP(), []int{9}
}

func (x *SizeData) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *SizeData) GetDealer() string {
	if x != nil {
		return x.Dealer
	}
	return ""
}

func (x *SizeData) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SizeData) GetPrepay() string {
	if x != nil {
		return x.Prepay
	}
	return ""
}

func (x *SizeData) GetOrderDate() string {
	if x != nil {
		return x.OrderDate
	}
	return ""
}

func (x *SizeData) GetReadyDate() string {
	if x != nil {
		return x.ReadyDate
	}
	return ""
}

func (x *SizeData) GetReserveEndDate() string {
	if x != nil {
		return x.ReserveEndDate
	}
	return ""
}

type CreatePostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title          string             `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	ForCatalog     bool               `protobuf:"varint,2,opt,name=for_catalog,json=forCatalog,proto3" json:"for_catalog,omitempty"`
	Price          map[string]float32 `protobuf:"bytes,3,rep,name=price,proto3" json:"price,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
	Specifications *Specifications    `protobuf:"bytes,4,opt,name=specifications,proto3" json:"specifications,omitempty"`
	Tags           []string           `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Variants       []*Variant         `protobuf:"bytes,6,rep,name=variants,proto3" json:"variants,omitempty"`
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metal_doors_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metal_doors_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_metal_doors_proto_rawDescGZIP(), []int{10}
}

func (x *CreatePostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePostRequest) GetForCatalog() bool {
	if x != nil {
		return x.ForCatalog
	}
	return false
}

func (x *CreatePostRequest) GetPrice() map[string]float32 {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *CreatePostRequest) GetSpecifications() *Specifications {
	if x != nil {
		return x.Specifications
	}
	return nil
}

func (x *CreatePostRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreatePostRequest) GetVariants() []*Variant {
	if x != nil {
		return x.Variants
	}
	return nil
}

type CreatePostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Id     string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreatePostResponse) Reset() {
	*x = CreatePostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metal_doors_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostResponse) ProtoMessage() {}

func (x *CreatePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metal_doors_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostResponse.ProtoReflect.Descriptor instead.
func (*CreatePostResponse) Descriptor() ([]byte, []int) {
	return file_metal_doors_proto_rawDescGZIP(), []int{11}
}

func (x *CreatePostResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreatePostResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SingleMetalDoorResponseVariant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InImages  []string `protobuf:"bytes,1,rep,name=in_images,json=inImages,proto3" json:"in_images,omitempty"`
	OutImages []string `protobuf:"bytes,2,rep,name=out_images,json=outImages,proto3" json:"out_images,omitempty"`
	InColor   string   `protobuf:"bytes,3,opt,name=in_color,json=inColor,proto3" json:"in_color,omitempty"`
	OutColor  string   `protobuf:"bytes,4,opt,name=out_color,json=outColor,proto3" json:"out_color,omitempty"`
	Hex       string   `protobuf:"bytes,5,opt,name=hex,proto3" json:"hex,omitempty"`
}

func (x *SingleMetalDoorResponseVariant) Reset() {
	*x = SingleMetalDoorResponseVariant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metal_doors_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleMetalDoorResponseVariant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleMetalDoorResponseVariant) ProtoMessage() {}

func (x *SingleMetalDoorResponseVariant) ProtoReflect() protoreflect.Message {
	mi := &file_metal_doors_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleMetalDoorResponseVariant.ProtoReflect.Descriptor instead.
func (*SingleMetalDoorResponseVariant) Descriptor() ([]byte, []int) {
	return file_metal_doors_proto_rawDescGZIP(), []int{5, 0}
}

func (x *SingleMetalDoorResponseVariant) GetInImages() []string {
	if x != nil {
		return x.InImages
	}
	return nil
}

func (x *SingleMetalDoorResponseVariant) GetOutImages() []string {
	if x != nil {
		return x.OutImages
	}
	return nil
}

func (x *SingleMetalDoorResponseVariant) GetInColor() string {
	if x != nil {
		return x.InColor
	}
	return ""
}

func (x *SingleMetalDoorResponseVariant) GetOutColor() string {
	if x != nil {
		return x.OutColor
	}
	return ""
}

func (x *SingleMetalDoorResponseVariant) GetHex() string {
	if x != nil {
		return x.Hex
	}
	return ""
}

var File_metal_doors_proto protoreflect.FileDescriptor

var file_metal_doors_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x2d, 0x64, 0x6f, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x22, 0x0e, 0x0a, 0x0c, 0x50, 0x6f,
	0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x30, 0x0a, 0x0d, 0x50, 0x6f,
	0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x65, 0x74, 0x61,
	0x6c, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xc0, 0x01, 0x0a,
	0x04, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x2c, 0x0a, 0x09, 0x69, 0x6e, 0x5f, 0x63, 0x6f, 0x6c, 0x6f,
	0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x6c,
	0x2e, 0x49, 0x6e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x73, 0x52, 0x08, 0x69, 0x6e, 0x43, 0x6f, 0x6c,
	0x6f, 0x72, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73,
	0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x75, 0x74, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x07,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x75, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x22,
	0x32, 0x0a, 0x08, 0x49, 0x6e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f,
	0x72, 0x12, 0x10, 0x0a, 0x03, 0x68, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x68, 0x65, 0x78, 0x22, 0x28, 0x0a, 0x16, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x4d, 0x65, 0x74,
	0x61, 0x6c, 0x44, 0x6f, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xfe, 0x02,
	0x0a, 0x17, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x6c, 0x44, 0x6f, 0x6f,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x0e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x6d, 0x65, 0x74, 0x61, 0x6c, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x42, 0x0a, 0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x2e, 0x53,
	0x69, 0x6e, 0x67, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x6c, 0x44, 0x6f, 0x6f, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x52, 0x08,
	0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x1a, 0x8f, 0x01, 0x0a,
	0x07, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x5f, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x75, 0x74, 0x5f, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x75, 0x74, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x6e, 0x5f, 0x63, 0x6f, 0x6c, 0x6f, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x6e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12,
	0x1b, 0x0a, 0x09, 0x6f, 0x75, 0x74, 0x5f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6f, 0x75, 0x74, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x10, 0x0a, 0x03,
	0x68, 0x65, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x68, 0x65, 0x78, 0x22, 0xc4,
	0x02, 0x0a, 0x0e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x65, 0x74,
	0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x12,
	0x12, 0x0a, 0x04, 0x6c, 0x65, 0x61, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x6c,
	0x65, 0x61, 0x66, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x70, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x63,
	0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x70, 0x65, 0x72, 0x4c, 0x6f,
	0x63, 0x6b, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x63, 0x6b,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x4c, 0x6f, 0x63,
	0x6b, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x76, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x76, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x72, 0x6d, 0x6f, 0x72,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x72, 0x6d, 0x6f, 0x72, 0x12, 0x1a, 0x0a,
	0x08, 0x63, 0x79, 0x6c, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x63, 0x79, 0x6c, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x65, 0x65,
	0x70, 0x68, 0x6f, 0x6c, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x65, 0x65,
	0x70, 0x68, 0x6f, 0x6c, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x73, 0x75, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x75, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x6c, 0x65, 0x72, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x61, 0x6c, 0x65, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x22, 0xb0, 0x01, 0x0a, 0x07, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x6e, 0x5f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x6e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x1b, 0x0a, 0x09,
	0x6f, 0x75, 0x74, 0x5f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6f, 0x75, 0x74, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x5f,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x75, 0x74, 0x5f, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x75, 0x74, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x2e, 0x53, 0x69, 0x7a, 0x65,
	0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x68, 0x65, 0x78, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x68, 0x65, 0x78, 0x22, 0x55, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x64, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x6c,
	0x2e, 0x53, 0x69, 0x7a, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0xd0, 0x01, 0x0a, 0x08, 0x53, 0x69, 0x7a, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x61, 0x6c, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x61, 0x6c, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x70, 0x61, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65, 0x70, 0x61, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x61,
	0x64, 0x79, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72,
	0x65, 0x61, 0x64, 0x79, 0x44, 0x61, 0x74, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x72, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x5f, 0x65, 0x6e, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x45, 0x6e, 0x64, 0x44, 0x61,
	0x74, 0x65, 0x22, 0xbe, 0x02, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x66, 0x6f, 0x72, 0x5f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0a, 0x66, 0x6f, 0x72, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x12,
	0x39, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x0e, 0x73, 0x70,
	0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0e, 0x73, 0x70, 0x65, 0x63, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x2a, 0x0a,
	0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x2e, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x52,
	0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x73, 0x1a, 0x38, 0x0a, 0x0a, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x3c, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x32, 0xe6, 0x01, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61, 0x6c, 0x44, 0x6f, 0x6f, 0x72, 0x73,
	0x41, 0x70, 0x69, 0x12, 0x39, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x12,
	0x13, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x2e, 0x50, 0x6f, 0x73,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x43,
	0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x18, 0x2e, 0x6d,
	0x65, 0x74, 0x61, 0x6c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65,
	0x4d, 0x65, 0x74, 0x61, 0x6c, 0x44, 0x6f, 0x6f, 0x72, 0x12, 0x1d, 0x2e, 0x6d, 0x65, 0x74, 0x61,
	0x6c, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x6c, 0x44, 0x6f, 0x6f,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x6c,
	0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x6c, 0x44, 0x6f, 0x6f, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_metal_doors_proto_rawDescOnce sync.Once
	file_metal_doors_proto_rawDescData = file_metal_doors_proto_rawDesc
)

func file_metal_doors_proto_rawDescGZIP() []byte {
	file_metal_doors_proto_rawDescOnce.Do(func() {
		file_metal_doors_proto_rawDescData = protoimpl.X.CompressGZIP(file_metal_doors_proto_rawDescData)
	})
	return file_metal_doors_proto_rawDescData
}

var file_metal_doors_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_metal_doors_proto_goTypes = []interface{}{
	(*PostsRequest)(nil),                   // 0: metal.PostsRequest
	(*PostsResponse)(nil),                  // 1: metal.PostsResponse
	(*Post)(nil),                           // 2: metal.Post
	(*InColors)(nil),                       // 3: metal.InColors
	(*SingleMetalDoorRequest)(nil),         // 4: metal.SingleMetalDoorRequest
	(*SingleMetalDoorResponse)(nil),        // 5: metal.SingleMetalDoorResponse
	(*Specifications)(nil),                 // 6: metal.Specifications
	(*Variant)(nil),                        // 7: metal.Variant
	(*Size)(nil),                           // 8: metal.Size
	(*SizeData)(nil),                       // 9: metal.SizeData
	(*CreatePostRequest)(nil),              // 10: metal.CreatePostRequest
	(*CreatePostResponse)(nil),             // 11: metal.CreatePostResponse
	(*SingleMetalDoorResponseVariant)(nil), // 12: metal.SingleMetalDoorResponse.variant
	nil,                                    // 13: metal.CreatePostRequest.PriceEntry
}
var file_metal_doors_proto_depIdxs = []int32{
	2,  // 0: metal.PostsResponse.data:type_name -> metal.Post
	3,  // 1: metal.Post.in_colors:type_name -> metal.InColors
	6,  // 2: metal.SingleMetalDoorResponse.specifications:type_name -> metal.Specifications
	12, // 3: metal.SingleMetalDoorResponse.variants:type_name -> metal.SingleMetalDoorResponse.variant
	8,  // 4: metal.Variant.size:type_name -> metal.Size
	9,  // 5: metal.Size.data:type_name -> metal.SizeData
	13, // 6: metal.CreatePostRequest.price:type_name -> metal.CreatePostRequest.PriceEntry
	6,  // 7: metal.CreatePostRequest.specifications:type_name -> metal.Specifications
	7,  // 8: metal.CreatePostRequest.variants:type_name -> metal.Variant
	0,  // 9: metal.MetalDoorsApi.GetPosts:input_type -> metal.PostsRequest
	10, // 10: metal.MetalDoorsApi.CreatePost:input_type -> metal.CreatePostRequest
	4,  // 11: metal.MetalDoorsApi.GetSingleMetalDoor:input_type -> metal.SingleMetalDoorRequest
	1,  // 12: metal.MetalDoorsApi.GetPosts:output_type -> metal.PostsResponse
	11, // 13: metal.MetalDoorsApi.CreatePost:output_type -> metal.CreatePostResponse
	5,  // 14: metal.MetalDoorsApi.GetSingleMetalDoor:output_type -> metal.SingleMetalDoorResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_metal_doors_proto_init() }
func file_metal_doors_proto_init() {
	if File_metal_doors_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_metal_doors_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metal_doors_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metal_doors_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Post); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metal_doors_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InColors); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metal_doors_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleMetalDoorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metal_doors_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleMetalDoorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metal_doors_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Specifications); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metal_doors_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Variant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metal_doors_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Size); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metal_doors_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SizeData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metal_doors_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metal_doors_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metal_doors_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleMetalDoorResponseVariant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_metal_doors_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metal_doors_proto_goTypes,
		DependencyIndexes: file_metal_doors_proto_depIdxs,
		MessageInfos:      file_metal_doors_proto_msgTypes,
	}.Build()
	File_metal_doors_proto = out.File
	file_metal_doors_proto_rawDesc = nil
	file_metal_doors_proto_goTypes = nil
	file_metal_doors_proto_depIdxs = nil
}
